

 cat LineInFileHttp.yaml
---
- hosts: all
  gather_facts: yes

  tasks:
  - name: "Changing the port of httpd"
    become: yes
    lineinfile:
      path: /etc/apache2/ports.conf
      regex: '^Listen 80'
      line: 'Listen 8080'
      backup: yes
    notify: Restart apache

  handlers:
  - name: "Restart apache"
    service:
      name: apache2
      state: restarted
