---
- hosts: all
  gather_facts: yes

  tasks:
  - name: "Add a user to the system"
    user:
      name: newuser
      state: present
      groups: sudo
      createhome: yes
    become: yes
    tags:
    - DeployUser
    - adduser

  - name: "Adding the Authorized keys"
    authorized_key:
      user: newuser
      key: "{{ item }}"
    with_file: /home/ansibleuser/.ssh/id_rsa.pub
    become: yes
    tags:
    - DeployUser
    - KeyAdd

#Commands Usage
ansible-playbook  TagsUserAdd.yaml --tag DeployUser -K // This will deploy both the tasks
ansible-playbook  TagsUserAdd.yaml --tag KeyAdd -K // This will execute only one task.



#To skip specifc tag
ansible-playbook  TagsUserAdd.yaml --skip-tags KeyAdd -K

#To have multiple Tags
ansible-playbook TagsUserAdd.yaml -t DeployUser,KeyAdd -K
