---

cat templates.yaml
- hosts: all
  gather_facts: yes

  vars:
    new_ip: 192.168.150.131
    new_name: webapp


  tasks:
  - name: "Copy the the /etc/hosts file"
    become: yes
    template:
      src: templates/hosts.j2
      dest: /etc/hosts


ansibleuser@ubuntu-master:~/playbooks$
ansibleuser@ubuntu-master:~/playbooks$ cat templates/hosts.j2
127.0.0.1       localhost
127.0.1.1       ubuntu-master
{{ new_ip }}    {{ new_name }}

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouter
