---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: "Restart Apache if configuration file is changed"
    service:
      name: httpd
      state: restarted
    when: ansible_facts['distribution'] == 'CentOS'
