---
- hosts: all
  gather_facts: yes

  vars:
    new_ip: 192.168.150.131
    new_name: webapp


  tasks:
  - name: "Copy the the /etc/hosts file"
    template:
      src: hosts.j2
      dest: /tmp/


